### ISSUE TITLE
怎样给ViewHolder传入点击事件？

### ISSUE THREAD

**Issue by notHide** [simplify20/PowerfulRecyclerViewAdapter#1]
看了下代码，点击事件是被封装在ViewHolder内部的，这样的话点击事件只能在ViewHolder里面做操作。    如果我想把点击事件从外部传入进去（比如用接口）该怎么实现呢？

**Comment by simplify20** [comment]
我猜你的需求是在Activity或者Fragment中处理点击事件是吧，目前的实现中Activity或者Fragment中只会出现[DataBean](https://github.com/simplify20/PowerfulRecyclerViewAdapter/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fsteve%2Fcreact%2Flibrary%2Fdisplay%2FDataBean.java)或者[DisplayBean](https://github.com/simplify20/PowerfulRecyclerViewAdapter/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fsteve%2Fcreact%2Flibrary%2Fdisplay%2FDisplayBean.java)，ViewHolder和Adapter是完全解耦的，而DataBean只有两个接口createHolder()和bindData()。以后会考虑在DisplayBean中增加传入Listener的接口的。另外欢迎pull request，一起参与，让项目更完善。

**Comment by simplify20** [comment]
另外在[CommonRecyclerAdapter](https://github.com/simplify20/PowerfulRecyclerViewAdapter/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fsteve%2Fcreact%2Flibrary%2Fadapter%2FCommonRecyclerAdapter.java)中也可以做的,比如这样:

``` java
    @Override
    public void onBindViewHolder(BaseRecyclerViewHolder holder, int position) {
        DisplayBean bindBean = data.get(position);
        setListener(holder,bindBean,position);//父类只提供空实现，子类有需要的话继承之
        if (bindBean instanceof DataBean) {
            ((DataBean) bindBean).bindData(holder);
        }
    }
```

继承CommonRecyclerAdapter，重写 setListener()：

``` java
    @Override
    public void setListener(BaseRecyclerViewHolder holder, DisplayBean bindBean,int position) {
      holder.setOnItemClickListener(listener);
      //...
    }
```

只是简单举个例子。

**Comment by notHide** [comment]
谢谢，了解了。
