### ISSUE TITLE
AS2.1.2无法进行编译了

### ISSUE THREAD

**Issue by hidetag** [simplify20/PowerfulRecyclerViewAdapter#2]
截止到7月26日，AS和SDK都是最新的
下午的时候突然无法编译，提示自动生成的所有Bean找不到，不存在
我试过了clean，invalidate caches and restart，重启AS，重启电脑，删除build目录，删除gradle中的PowerfulAapter的配置，然后重新添加依赖，依然都是不行的。。

**Comment by simplify20** [comment]
```
        classpath 'com.android.tools.build:gradle:2.1.0'
        // the latest version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
```

你的android plugin 和 android-apt 版本对吗，我怀疑是版本问题

**Comment by hidetag** [comment]
抱歉，问题找到了，是ButterKnife注解的时候，xml中我删除了某个控件，但是代码中注解依然存在忘记删除，导致编译失败，但是报错一直指向PowerfulRecyclerViewAdapter的注解DataBean
